In [1]:
import pandas as pd
wine = pd.read_csv("https://bit.ly/wine_csv_data")

In [2]:
data=wine[["alcohol","sugar","pH"]].to_numpy()
target = wine["class"].to_numpy()

In [3]:
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [4]:
# 트레인 데이터를 서브 데이터와 검증 데이터로 또 나눔
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, test_size=0.2, random_state=42)

In [5]:
print(sub_input.shape, val_input.shape, test_input.shape)
print(sub_target.shape, val_target.shape, test_target.shape)

(4157, 3) (1040, 3) (1300, 3)
(4157,) (1040,) (1300,)


In [6]:
# 서브 데이터로 결정트리 학습후, 서브 데이터와 검증 데이터의 정확도를 구함
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)
print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077


In [7]:
# cross_validate() 메서드 : 교차검증 함수
# cv 매개변수 : 교차 검증 분할 수
from sklearn.model_selection import cross_validate
scores = cross_validate(dt, train_input, train_target)
scores

{'fit_time': array([0.00943923, 0.00748038, 0.00745583, 0.00750923, 0.00708461]),
 'score_time': array([0.00112581, 0.00081325, 0.00076556, 0.00079107, 0.0007906 ]),
 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}

In [8]:
import numpy as np
print(np.mean(scores["test_score"]))

0.855300214703487


In [9]:
# StratifiedKFold() : 타깃 클래스를 골고루 나눠줌
from sklearn.model_selection import StratifiedKFold
scores = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
print(np.mean(scores["test_score"]))

0.855300214703487


In [10]:
# n_splits 매개변수 : 구간을 몇개로 나눌지 결정
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [11]:
print(splitter)

StratifiedKFold(n_splits=10, random_state=42, shuffle=True)


In [12]:
scores = cross_validate(dt, train_input, train_target, cv=splitter)
print(np.mean(scores["test_score"]))

0.8574181117533719


##하이퍼파라미터 튜닝 p.248

In [13]:
# GridSearchCV 클래스 : 하이퍼파라미터 탐색과 교차 검증을 한 번에 수행해줌
from sklearn.model_selection import GridSearchCV
params = {"min_impurity_decrease":[0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

In [14]:
# n_jobs 매개변수 : 병렬 실행에 사용할 CPU 코어 수를 지정
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)

In [15]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [16]:
# best_estimator_ 속성 : 여러 모델중에서 검증 점수가 가장 높은 모델
dt = gs.best_estimator_
print(dt.score(train_input, train_target))

0.9615162593804117


In [17]:
# best_params_ 속성 : 최적의 매개변수
print(gs.best_params_)

{'min_impurity_decrease': 0.0001}


In [18]:
print(gs.cv_results_["mean_test_score"])

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [19]:
best_index = np.argmax(gs.cv_results_["mean_test_score"])
print(gs.cv_results_["params"][best_index])
print(best_index)

{'min_impurity_decrease': 0.0001}
0


In [20]:
params = {"min_impurity_decrease" : np.arange(0.0001, 0.001, 0.0001),
          "max_depth" : range(5,20,1),
          "min_samples_split" : range(2,100,10)}

In [21]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [22]:
import multiprocessing
cores = multiprocessing.cpu_count()
print(cores)

2


In [23]:
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': 0.0004, 'min_samples_split': 12}


In [24]:
print(np.max(gs.cv_results_["mean_test_score"]))

0.8683865773302731


###랜덤 서치

In [25]:
from scipy.stats import uniform, randint
rgen = randint(0,10)
rgen.rvs(10)

array([9, 7, 5, 6, 2, 7, 4, 5, 3, 6])

In [26]:
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 98, 111, 109,  88, 117,  84,  96, 113,  95,  89]))

In [27]:
ugen = uniform(0,1)
ugen.rvs(10)

array([0.9148799 , 0.31118951, 0.95722662, 0.58286966, 0.93716333,
       0.84271842, 0.29632173, 0.27728256, 0.35652215, 0.98300658])

In [28]:
params = {"min_impurity_decrease" : uniform(0.0001, 0.001),
          "max_depth" : randint(20, 50),
          "min_samples_split" : randint(2, 25),
          "min_samples_leaf" : randint(1, 25),}

In [29]:
from sklearn.model_selection import RandomizedSearchCV
gs = RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params,
                        n_iter=100, n_jobs=-1, random_state=42)
gs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f6e846f0090>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f6e846de690>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f6e846f02d0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7f6e846f0e10>},
                   random_state=42)

In [30]:
print(gs.best_params_)

{'max_depth': 39, 'min_impurity_decrease': 0.00034102546602601173, 'min_samples_leaf': 7, 'min_samples_split': 13}


In [31]:
print(np.max(gs.cv_results_["mean_test_score"]))

0.8695428296438884


In [32]:
dt = gs.best_estimator_
print(dt.score(test_input, test_target))

0.86


예제

In [33]:
gs = RandomizedSearchCV(DecisionTreeClassifier(splitter="random", random_state=42), params,
                        n_iter=100, n_jobs=-1, random_state=42)
gs.fit(train_input, train_target)
print(gs.best_params_)
print(np.max(gs.cv_results_["mean_test_score"]))
dt = gs.best_estimator_
print(dt.score(test_input, test_target))

{'max_depth': 43, 'min_impurity_decrease': 0.00011407982271508446, 'min_samples_leaf': 19, 'min_samples_split': 18}
0.8458726956392981
0.786923076923077
